apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yp969803/argo-tut.git
    targetRevision: HEAD
    path: enviroments/staging/my-app
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true 
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true


